# Set default terminal to support 256 colors
set -g default-terminal "tmux-256color"

# Support 24-bit true color
set-option -sa terminal-overrides ",xterm*:Tc"

# Enable mouse support (clickable windows, panes, resizable panes)
set -g mouse on

# prefix
unbind C-b
# set -g prefix C-Space
# bind C-Space send-prefix
set -g prefix S-F3
bind S-F3 send-prefix

# split panes
unbind '"'
unbind %
bind - split-window -v -c "#{pane_current_path}"
bind '\' split-window -h -c "#{pane_current_path}"


# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on


# Split panes open in current working directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"


#  Status bar
set -g status-position bottom
set -g status-interval 5
set -g status-style "bg=#363142,fg=#b8b0c4"

set -g status-left ""
set -g status-right-length 50
set -g status-right "#[fg=#8aadf4]%b %d, %Y #[fg=#8aadf4]| #[fg=#8aadf4]%-I:%M %p" # blue:8aadf4 yellow:fcbd72
set -g window-status-separator ""

# Inactive window
set -g window-status-format \
"#[bg=#363142,fg=#aaa2b5] #I:#{?window_activity_flag,*,} #W "

# Active window
set -g window-status-current-format \
"#[bg=#fcbd72,fg=#24273a,bold] #I: #W "

# Use application names for window names
set -g automatic-rename on
set -g automatic-rename-format "#{pane_current_command}"

# Reload config
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded!"

# Active/selected pane border
set -g pane-active-border-style "fg=#fcbd72"



# tdo soirce ros